### ISSUE TITLE
does this script still work?

### ISSUE THREAD

**Issue by Akira46** [Kellphy/Nodepay#1]
hi, does this script still work? I have run it and it works. but since yesterday it hasn't worked and I tried visiting the website https://app.nodepay.ai/ there is captcha verification.

**Comment by Kellphy** [comment]
Fix is on the way

**Comment by Kellphy** [comment]
Deployed new version using cookie login to bypass the captcha. Check the Setup instructions, it's pretty fast. I'll monitor it, but let me know if there are any other issues. Take care!

https://github.com/Kellphy/Nodepay/blob/main/README.md
