### ISSUE TITLE
Not working any longer 

### ISSUE THREAD

**Issue by graboosky** [Kellphy/Nodepay#3]
Hi, great job, it was working perfectly well with your cookie update. Just to let you know I think it doesn't work any longer for about ~24h. Could you confirm of it works for you or not?

**Comment by vstrong-info** [comment]
All is working ok

**Comment by graboosky** [comment]
Thanks for replly, I will wait another 48h, maybe it is something on project side itself.

**Comment by Kellphy** [comment]
I can confirm that it works, if it's stuck to "checking login page", try to reassign the new cookie value :)
